openapi: 3.0.0
info:
  title: Composer API
  version: '1.0.0'
tags:
- name: Composers
paths:
  /composers:
    description: The Composer API
    get:
      tags:
      - "Composers"
      summary: Returns a list of composer documents
      description: |
        API for returning a list of composers from MongoDB Atlas
      responses:
        '200':
          description: |
            Composer documents
        '500':
          description: |
            Server Exception
        '501':
          description: |
            MongoDB Exception
    post:
      tags:
      - "Composers"
      summary: 
        Creates a new composer object
      description: |
        API for adding new composer object
      requestBody:
        description:
          Composer's Information
        content:
          application/json:
            schema:
              type: "object"
              properties:
                firstName:
                  type: "string"
                lastName:
                  type: "string"
      responses:
        '200':
          description: |
            Composer added
        '500':
          description: |
            Server Exception
        '501':
          description: |
            MongoDB Exception
  '/composers/{id}':
    description: Composer API
    get:
      tags:
      - "Composers"
      summary: returns a composer document
      description: API for returning a single composer object from MongoDB
      parameters:
        - in: path
          name: id
          description: the composer id requested by the user
          required: true
          schema:
            type: string
            description: the composer id requested by the user
      responses:
        '200':
          description: |
            Composer added
        '500':
          description: |
            Server Exception
        '501':
          description: |
            MongoDB Exception
            
            
            
            
            
            
